### ISSUE TITLE
Umbrella issue to revise/add contents

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes-sigs/prow#31]
Ref: https://github.com/kubernetes-sigs/prow/issues/4#issuecomment-1291525777
> The final step is to update/reorganize/rearrange the contents from the Legacy Snapshot. However we can also just add new content on the side, and later mark things in the Legacy Snapshot as being "dated". The one benefit of the Legacy Snapshot is that at least we get a table-of-contents of every single Prow markdown file, which was previously only discoverable via grepping through the sources (or through enough determined mouse clicks). So in this sense it's something that can happen over a longer period of time. Most likely things will happen organically here.

Anyone that can edit this issue body might update the task list below.

[Common TODO: check, and revise if needed]
- [ ] [Announcements](https://docs.prow.k8s.io/docs/announcements/)
- [ ] [Overview](https://docs.prow.k8s.io/docs/overview/)
	- [ ] [Architecture](https://docs.prow.k8s.io/docs/overview/architecture/)
- [ ] [Components](https://docs.prow.k8s.io/docs/components/)
	- [ ] **[Core Components](https://docs.prow.k8s.io/docs/components/core/): Doc content is empty.**
		- [ ] [Crier](https://docs.prow.k8s.io/docs/components/core/crier/)
		- [ ] [Deck](https://docs.prow.k8s.io/docs/components/core/deck/)
			- [ ] [How to setup GitHub Oauth](https://docs.prow.k8s.io/docs/components/core/deck/github-oauth-setup/)
			- [ ] [CSRF attacks](https://docs.prow.k8s.io/docs/components/core/deck/csrf/)
		- [ ] **[Hook](https://docs.prow.k8s.io/docs/components/core/hook/): Doc content is empty.**
		- [ ] **[Horologium](https://docs.prow.k8s.io/docs/components/core/horologium/): Doc content is empty.**
		- [ ] [Prow-Controller-Manager](https://docs.prow.k8s.io/docs/components/core/prow-controller-manager/)
		- [ ] **[Sinker](https://docs.prow.k8s.io/docs/components/core/sinker/): Doc content is empty.**
		- [ ] [Tide](https://docs.prow.k8s.io/docs/components/core/tide/)
			- [ ] [Configuring Tide](https://docs.prow.k8s.io/docs/components/core/tide/config/)
			- [ ] [Maintainer's Guide to Tide](https://docs.prow.k8s.io/docs/components/core/tide/maintainers/)
			- [ ] [PR Author's Guide to Tide](https://docs.prow.k8s.io/docs/components/core/tide/pr-authors/)
	- [ ] **[Optional Components](https://docs.prow.k8s.io/docs/components/optional/): Doc content is empty.**
		- [ ] [Branchprotector](https://docs.prow.k8s.io/docs/components/optional/branchprotector/)
		- [ ] [Exporter](https://docs.prow.k8s.io/docs/components/optional/exporter/)
		- [ ] [gcsupload](https://docs.prow.k8s.io/docs/components/optional/gcsupload/)
		- [ ] [Gerrit](https://docs.prow.k8s.io/docs/components/optional/gerrit/)
		- [ ] [HMAC](https://docs.prow.k8s.io/docs/components/optional/hmac/)
		- [ ] [jenkins-operator](https://docs.prow.k8s.io/docs/components/optional/jenkins-operator/)
		- [ ] [status-reconciler](https://docs.prow.k8s.io/docs/components/optional/status-reconciler/)
		- [ ] **[tot](https://docs.prow.k8s.io/docs/components/optional/tot/): Doc content is empty.**
			- [ ] [fallbackcheck](https://docs.prow.k8s.io/docs/components/optional/tot/fallbackcheck/)
		- [ ] [Sub](https://docs.prow.k8s.io/docs/components/optional/sub/)
	- [ ] **[CLI Tools](https://docs.prow.k8s.io/docs/components/cli-tools/): Doc content is empty.**
		- [ ] [checkconfig](https://docs.prow.k8s.io/docs/components/cli-tools/checkconfig/)
		- [ ] [config-bootstrapper](https://docs.prow.k8s.io/docs/components/cli-tools/config-bootstrapper/)
		- [ ] [generic-autobumper](https://docs.prow.k8s.io/docs/components/cli-tools/generic-autobumper/)
		- [ ] [invitations-accepter](https://docs.prow.k8s.io/docs/components/cli-tools/invitations-accepter/)
		- [ ] **[mkpj](https://docs.prow.k8s.io/docs/components/cli-tools/mkpj/): Doc content is empty.**
		- [ ] **[mkpod](https://docs.prow.k8s.io/docs/components/cli-tools/mkpod/): Doc content is empty.**
		- [ ] [Peribolos](https://docs.prow.k8s.io/docs/components/cli-tools/peribolos/)
		- [ ] [Phaino](https://docs.prow.k8s.io/docs/components/cli-tools/phaino/)
		- [ ] [Phony](https://docs.prow.k8s.io/docs/components/cli-tools/phony/)
	- [ ] [Pod Utilities](https://docs.prow.k8s.io/docs/components/pod-utilities/)
		- [ ] [clonerefs](https://docs.prow.k8s.io/docs/components/pod-utilities/clonerefs/)
		- [ ] [entrypoint](https://docs.prow.k8s.io/docs/components/pod-utilities/entrypoint/)
		- [ ] [initupload](https://docs.prow.k8s.io/docs/components/pod-utilities/initupload/)
		- [ ] [sidecar](https://docs.prow.k8s.io/docs/components/pod-utilities/sidecar/)
	- [ ] [Plugins](https://docs.prow.k8s.io/docs/components/plugins/)
		- [ ] **[approve](https://docs.prow.k8s.io/docs/components/plugins/approve/): Doc content is empty.**
			- [ ] [Reviewers and Approvers](https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/)
		- [ ] [branchcleaner](https://docs.prow.k8s.io/docs/components/plugins/branchcleaner/)
		- [ ] [lgtm](https://docs.prow.k8s.io/docs/components/plugins/lgtm/)
		- [ ] [updateconfig](https://docs.prow.k8s.io/docs/components/plugins/updateconfig/)
	- [ ] **[External Plugins](https://docs.prow.k8s.io/docs/components/external-plugins/): Doc content is empty.**
		- [ ] [cherrypicker](https://docs.prow.k8s.io/docs/components/external-plugins/cherrypicker/)
	- [ ] [Deprecated Components](https://docs.prow.k8s.io/docs/components/deprecated/)
		- [ ] [cm2kc (clustermap to kubeconfig)](https://docs.prow.k8s.io/docs/components/deprecated/cm2kc/)
		- [ ] [Plank](https://docs.prow.k8s.io/docs/components/deprecated/plank/)
	- [ ] [Undocumented Components](https://docs.prow.k8s.io/docs/components/undocumented/)
		- [ ] **[admission](https://docs.prow.k8s.io/docs/components/undocumented/admission/): Doc content is empty.**
		- [ ] **[grandmatriarch](https://docs.prow.k8s.io/docs/components/undocumented/grandmatriarch/): Doc content is empty.**
		- [ ] **[pipeline](https://docs.prow.k8s.io/docs/components/undocumented/pipeline/): Doc content is empty.**
		- [ ] **[tackle](https://docs.prow.k8s.io/docs/components/undocumented/tackle/): Doc content is empty. See #32**
- [ ] (We might add some categories for below pages.
  For now these pages are just placed in the top-level directory of the Prow docs codebase.)
- [ ] [GKE Build Clusters](https://docs.prow.k8s.io/docs/build-clusters/)
- [ ] [Contribution Guidelines](https://docs.prow.k8s.io/docs/contribution-guidelines/)
- [ ] [Metrics](https://docs.prow.k8s.io/docs/metrics/)
- [ ] [Building, Testing, and Updating Prow](https://docs.prow.k8s.io/docs/build-test-update/)
- [ ] [Deploying Prow](https://docs.prow.k8s.io/docs/getting-started-deploy/)
- [ ] [Developing and Contributing to Prow](https://docs.prow.k8s.io/docs/getting-started-develop/)
- [ ] [Getting more out of Prow](https://docs.prow.k8s.io/docs/more-prow/)
- [ ] [GitHub API Library](https://docs.prow.k8s.io/docs/github/)
- [ ] [Inrepoconfig](https://docs.prow.k8s.io/docs/inrepoconfig/)
- [ ] [Life of a Prow Job](https://docs.prow.k8s.io/docs/life-of-a-prow-job/)
- [ ] [Prow Configuration](https://docs.prow.k8s.io/docs/config/)
- [ ] [Prow Secrets Management](https://docs.prow.k8s.io/docs/prow-secrets/)
- [ ] [Gerrit](https://docs.prow.k8s.io/docs/gerrit/)
- [ ] [ProwJobs](https://docs.prow.k8s.io/docs/jobs/)
- [ ] [Setting up Private Deck](https://docs.prow.k8s.io/docs/private-deck/)
- [ ] [Spyglass](https://docs.prow.k8s.io/docs/spyglass/)
	- [ ] [Spyglass Architecture](https://docs.prow.k8s.io/docs/spyglass/architecture/)
	- [ ] [Build a Spyglass Lens](https://docs.prow.k8s.io/docs/spyglass/write-a-lens/)
	- [ ] [REST API coverage lens](https://docs.prow.k8s.io/docs/spyglass/lenses/restcoverage/)
- [ ] [Using Prow at Scale](https://docs.prow.k8s.io/docs/scaling/)
- [ ] [Understanding Started.json and Finished.json](https://docs.prow.k8s.io/docs/metadata-artifacts/)
- [ ] [Testing Prow](https://docs.prow.k8s.io/docs/test/)
	- [ ] [Run Prow integration tests](https://docs.prow.k8s.io/docs/test/integration/): We might update the 'Code layout' section.
		- [ ] [Fake Git Server (FGS)](https://docs.prow.k8s.io/docs/test/integration/fakegitserver/)
		- [ ] (We might add [other `fake*` series](https://github.com/kubernetes/test-infra/tree/master/prow/test/integration/cmd) here.)
- [ ] [Legacy Snapshot](https://docs.prow.k8s.io/docs/legacy-snapshot/): would it be okay to remove/hide this page?
